import request from '../utils/request'
export const listCases = (path, params) => request.get(path, { params })
export const getCase = (path, id) => request.get(`${path}/${id}`)
export const createCase = (data) => request.post('/client/cases', data)
export const updateCase = (id, data) => request.put(`/client/cases/${id}`, data)
export const submitCase = (id) => request.post(`/client/cases/${id}/submit`)
export const reviewCase = (id, data) => request.post(`/admin/cases/${id}/review`, data)
export const assignCase = (id, data, reassign = false) => request.post(`/admin/cases/${id}/${reassign ? 'reassign' : 'assign'}`, data)
export const caseChildren = (id, resource, params) => request.get(`/cases/${id}/${resource}`, { params })
export const createStage = (id, data) => request.post(`/cases/${id}/stages`, data)
export const updateStage = (id, data) => request.put(`/case-stages/${id}`, data)
