import request from '../utils/request'
export const listWorkItems = (params) => request.get('/work-items', { params })
export const createWorkItem = (data) => request.post('/work-items', data)
export const startWorkItem = (id, data) => request.post(`/work-items/${id}/start`, data || {})
export const completeWorkItem = (id) => request.post(`/work-items/${id}/complete`)
export const addDependency = (id, data) => request.post(`/work-items/${id}/dependencies`, data)
export const listTimesheets = (params) => request.get('/timesheets', { params })
export const createTimesheet = (data) => request.post('/timesheets', data)
export const deleteTimesheet = (id) => request.delete(`/timesheets/${id}`)
export const listOcrJobs = (params) => request.get('/ocr-jobs', { params })
export const confirmOcrJob = (id, data) => request.post(`/ocr-jobs/${id}/confirm`, data || {})
export const retryOcrJob = (id) => request.post(`/ocr-jobs/${id}/retry`)
export const listRisks = (params) => request.get('/risks', { params })
export const caseRisks = (id) => request.get(`/cases/${id}/risks`)
export const documentVersions = (id) => request.get(`/documents/${id}/versions`)
export const uploadVersion = (id, data) => request.post(`/documents/${id}/versions`, data)
export const caseWorkflow = (id) => request.get(`/cases/${id}/workflow`)
export const fireWorkflow = (id, event, data) => request.post(`/cases/${id}/workflow/events/${event}`, data || {})
export const caseChecklists = (id) => request.get(`/cases/${id}/checklists`)
export const checkItem = (id, data) => request.put(`/checklist-items/${id}`, data)
export const addCollaborator = (id, data) => request.post(`/cases/${id}/collaborators`, data)
export const removeCollaborator = (id, assignmentId) => request.delete(`/cases/${id}/collaborators/${assignmentId}`)
export const recommendAgents = (caseId) => request.get('/admin/agent-recommendations', { params: { caseId } })
export const adjustDeadline = (id, data) => request.post(`/deadlines/${id}/adjust`, data)
export const deadlineHistory = (id) => request.get(`/deadlines/${id}/history`)
export const listExceptions = (params) => request.get('/admin/exceptions', { params })
export const resolveException = (id, data) => request.post(`/admin/exceptions/${id}/resolve`, data)
export const assignException = (id, data) => request.put(`/admin/exceptions/${id}/assign`, data)
export const scanDataQuality = () => request.get('/admin/data-quality')
export const listWorkflows = (params) => request.get('/admin/workflows', { params })
export const createWorkflow = (data) => request.post('/admin/workflows', data)
export const publishWorkflowVersion = (id) => request.post(`/admin/workflow-versions/${id}/publish`)
export const newWorkflowVersion = (id) => request.post(`/admin/workflows/${id}/versions`)
export const listDeadlineRules = (params) => request.get('/admin/deadline-rules', { params })
export const saveDeadlineRule = (data) => data.id
  ? request.put(`/admin/deadline-rules/${data.id}`, data)
  : request.post('/admin/deadline-rules', data)
export const listCalendars = (params) => request.get('/admin/business-calendar', { params })
export const listCalendarDays = (id, params) => request.get(`/admin/business-calendar/${id}/days`, { params })
export const upsertCalendarDay = (id, data) => request.post(`/admin/business-calendar/${id}/days`, data)
