<script setup>
import { onMounted, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { listCases, submitCase } from '../../api/case'
import { session } from '../../utils/session'
import { options, text, tagType, formatDate } from '../../utils/enums'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../../components/PageHeader.vue';import AppPagination from '../../components/AppPagination.vue'
const router=useRouter();const role=session.user.role;const base=`/${role.toLowerCase()}`;const state=reactive({list:[],total:0,pageNum:1,pageSize:10,keyword:'',status:'',caseType:'',loading:false})
const load=async()=>{state.loading=true;try{const r=await listCases(`${base}/cases`,{pageNum:state.pageNum,pageSize:state.pageSize,keyword:state.keyword||undefined,status:state.status||undefined,caseType:state.caseType||undefined});state.list=r.data.list;state.total=r.data.total}finally{state.loading=false}}
const submit=async(row)=>{await ElMessageBox.confirm('提交后进入管理员审核，确认继续？','提交委托');await submitCase(row.id);ElMessage.success('已提交审核');load()}
onMounted(load)
</script>
<template><div class="page"><PageHeader :title="role==='CLIENT'?'我的案件':role==='AGENT'?'我的承办案件':'全部案件'" description="按状态、类型和名称检索案件"><el-button v-if="role==='CLIENT'" type="primary" @click="router.push('/client/cases/create')">新建委托</el-button></PageHeader><div class="toolbar"><div class="filters"><el-input v-model="state.keyword" class="filter-input" placeholder="案件名称" clearable @keyup.enter="state.pageNum=1;load()"/><el-select v-model="state.caseType" class="filter-select" placeholder="案件类型" clearable><el-option v-for="o in options('caseType')" :key="o.value" v-bind="o"/></el-select><el-select v-model="state.status" class="filter-select" placeholder="案件状态" clearable><el-option v-for="o in options('caseStatus')" :key="o.value" v-bind="o"/></el-select><el-button type="primary" @click="state.pageNum=1;load()">查询</el-button></div></div><div class="table-wrap"><el-table v-loading="state.loading" :data="state.list" @row-dblclick="(r)=>router.push(`${base}/cases/${r.id}`)"><el-table-column prop="caseNo" label="案件编号" width="150"><template #default="{row}"><span class="mono">{{row.caseNo||'审核后生成'}}</span></template></el-table-column><el-table-column prop="caseName" label="案件名称" min-width="220" show-overflow-tooltip/><el-table-column label="类型" width="110"><template #default="{row}">{{text('caseType',row.caseType)}}</template></el-table-column><el-table-column prop="currentStage" label="当前阶段" width="120"/><el-table-column label="状态" width="115"><template #default="{row}"><el-tag :type="tagType(row.status)">{{text('caseStatus',row.status)}}</el-tag></template></el-table-column><el-table-column label="优先级" width="85"><template #default="{row}"><el-tag :type="tagType(row.priorityLevel)" effect="plain">{{text('priority',row.priorityLevel)}}</el-tag></template></el-table-column><el-table-column label="提交时间" width="150"><template #default="{row}">{{formatDate(row.submitTime)}}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="router.push(`${base}/cases/${row.id}`)">详情</el-button><el-button v-if="role==='CLIENT'&&['SUBMITTED','RETURNED'].includes(row.status)" link type="success" @click="submit(row)">提交</el-button></template></el-table-column></el-table></div><AppPagination v-model:page="state.pageNum" v-model:size="state.pageSize" :total="state.total" @change="load"/></div></template>
