<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft } from '@element-plus/icons-vue'
import { getCase, submitCase } from '../../api/case'
import { session } from '../../utils/session'
import { text, tagType, formatDate } from '../../utils/enums'
import { ElMessage, ElMessageBox } from 'element-plus'
import BasicInfoTab from './components/BasicInfoTab.vue';import ProgressTab from './components/ProgressTab.vue';import DocumentTab from './components/DocumentTab.vue';import DeadlineTab from './components/DeadlineTab.vue';import BillingTab from './components/BillingTab.vue';import WorkItemTab from './components/WorkItemTab.vue';import RiskTab from './components/RiskTab.vue'
const route=useRoute();const router=useRouter();const active=ref('basic');const item=ref({});const loading=ref(true);const role=session.user.role;const base=`/${role.toLowerCase()}`
const id=computed(()=>Number(route.params.id));const load=async()=>{loading.value=true;try{item.value=(await getCase(`${base}/cases`,id.value)).data}finally{loading.value=false}}
const submit=async()=>{await ElMessageBox.confirm('确认提交管理员审核？','提交委托');await submitCase(id.value);ElMessage.success('已提交');load()};onMounted(load)
</script>
<template><div v-loading="loading" class="page"><el-button link :icon="ArrowLeft" @click="router.push(`${base}/cases`)">返回案件列表</el-button><div class="detail-summary"><div><span class="mono">{{item.caseNo||'尚未立案'}}</span><h1>{{item.caseName}}</h1><div class="summary-meta"><span>类型：{{text('caseType',item.caseType)}}</span><span>阶段：{{item.currentStage||'—'}}</span><span>提交：{{formatDate(item.submitTime)}}</span><span>主办：{{item.principalAgentId||'—'}}</span></div></div><div class="detail-summary-actions"><el-tag :type="tagType(item.status)" size="large">{{text('caseStatus',item.status)}}</el-tag><el-button v-if="role==='CLIENT'&&['SUBMITTED','RETURNED'].includes(item.status)" @click="router.push(`/client/cases/${id}/edit`)">编辑资料</el-button><el-button v-if="role==='CLIENT'&&['SUBMITTED','RETURNED'].includes(item.status)" type="primary" @click="submit">提交审核</el-button></div></div><el-tabs v-if="item.id" v-model="active" class="detail-tabs"><el-tab-pane label="基本信息" name="basic" lazy><BasicInfoTab :case-info="item" @updated="load"/></el-tab-pane><el-tab-pane label="进度时间轴" name="progress" lazy><ProgressTab :case-id="id" @updated="load"/></el-tab-pane><el-tab-pane label="Work Items" name="work" lazy><WorkItemTab :case-id="id"/></el-tab-pane><el-tab-pane label="文件与官文" name="documents" lazy><DocumentTab :case-id="id"/></el-tab-pane><el-tab-pane label="时限任务" name="deadlines" lazy><DeadlineTab :case-id="id"/></el-tab-pane><el-tab-pane label="风险" name="risks" lazy><RiskTab :case-id="id"/></el-tab-pane><el-tab-pane v-if="role!=='AGENT'" label="账单费用" name="billing" lazy><BillingTab :case-id="id"/></el-tab-pane></el-tabs></div></template>
