<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createContact, deleteContact, listContacts, updateContact } from '../../api/client'
import { messageOf } from '../../utils/request'
import PageHeader from '../../components/PageHeader.vue'; import AppPagination from '../../components/AppPagination.vue'
const state=reactive({list:[],total:0,pageNum:1,pageSize:10,loading:false});const open=ref(false);const form=reactive({id:null,name:'',position:'',phone:'',email:'',permissionScope:'ALL_CASES',remark:''})
const load=async()=>{state.loading=true;try{const r=await listContacts(state);state.list=r.data.list;state.total=r.data.total}finally{state.loading=false}}
const edit=(row={})=>{Object.assign(form,{id:null,name:'',position:'',phone:'',email:'',permissionScope:'ALL_CASES',remark:'',...row});open.value=true}
const save=async()=>{try{const payload={name:form.name,position:form.position,phone:form.phone,email:form.email,permissionScope:form.permissionScope,remark:form.remark};form.id?await updateContact(form.id,payload):await createContact(payload);ElMessage.success('联系人已保存');open.value=false;load()}catch(e){ElMessage.error(messageOf(e))}}
const remove=async(row)=>{await ElMessageBox.confirm(`确认删除联系人“${row.name}”？`,'删除确认',{type:'warning'});await deleteContact(row.id);ElMessage.success('已删除');load()}
onMounted(load)
</script>
<template><div class="page"><PageHeader title="企业联系人" description="维护业务与财务联系人员"><el-button type="primary" @click="edit()">新增联系人</el-button></PageHeader><div class="table-wrap"><el-table v-loading="state.loading" :data="state.list"><el-table-column prop="name" label="姓名"/><el-table-column prop="position" label="职位"/><el-table-column prop="phone" label="电话"/><el-table-column prop="email" label="邮箱" min-width="180"/><el-table-column prop="permissionScope" label="权限范围"/><el-table-column label="操作" width="130"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></div><AppPagination v-model:page="state.pageNum" v-model:size="state.pageSize" :total="state.total" @change="load"/><el-dialog v-model="open" :title="form.id?'编辑联系人':'新增联系人'" width="min(560px,94vw)"><el-form class="form-grid" label-position="top"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="职位"><el-input v-model="form.position"/></el-form-item><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="权限范围"><el-select v-model="form.permissionScope"><el-option label="全部案件" value="ALL_CASES"/><el-option label="指定案件" value="SPECIFIED_CASES"/><el-option label="仅财务" value="FEE_ONLY"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
